// <auto-generated />
using System;
using FinDistill.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinDistill.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinDistillDbContext))]
    [Migration("20260306192358_AddDataMartViews")]
    partial class AddDataMartViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinDistill.Domain.Entities.DimAsset", b =>
                {
                    b.Property<int>("AssetKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetKey"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AssetKey");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("IX_DimAssets_Ticker");

                    b.ToTable("DimAssets", "dwh");
                });

            modelBuilder.Entity("FinDistill.Domain.Entities.DimDate", b =>
                {
                    b.Property<int>("DateKey")
                        .HasColumnType("int");

                    b.Property<byte>("Day")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("FullDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("bit");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Quarter")
                        .HasColumnType("tinyint");

                    b.Property<byte>("WeekOfYear")
                        .HasColumnType("tinyint");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("DateKey");

                    b.HasIndex("FullDate")
                        .IsUnique()
                        .HasDatabaseName("IX_DimDates_FullDate");

                    b.ToTable("DimDates", "dwh");
                });

            modelBuilder.Entity("FinDistill.Domain.Entities.DimSource", b =>
                {
                    b.Property<int>("SourceKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceKey"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SourceKey");

                    b.HasIndex("SourceName")
                        .IsUnique()
                        .HasDatabaseName("IX_DimSources_SourceName");

                    b.ToTable("DimSources", "dwh");
                });

            modelBuilder.Entity("FinDistill.Domain.Entities.FactQuote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AssetKey")
                        .HasColumnType("int");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("DateKey")
                        .HasColumnType("int");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("SourceKey")
                        .HasColumnType("int");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("DateKey");

                    b.HasIndex("SourceKey");

                    b.HasIndex("AssetKey", "DateKey", "SourceKey")
                        .IsUnique()
                        .HasDatabaseName("IX_FactQuotes_Asset_Date_Source");

                    b.ToTable("FactQuotes", "dwh");
                });

            modelBuilder.Entity("FinDistill.Domain.Entities.RawIngestData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsProcessed")
                        .HasDatabaseName("IX_RawIngestData_Unprocessed");

                    b.ToTable("RawIngestData", "lake");
                });

            modelBuilder.Entity("FinDistill.Domain.Entities.FactQuote", b =>
                {
                    b.HasOne("FinDistill.Domain.Entities.DimAsset", "Asset")
                        .WithMany("FactQuotes")
                        .HasForeignKey("AssetKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinDistill.Domain.Entities.DimDate", "Date")
                        .WithMany("FactQuotes")
                        .HasForeignKey("DateKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinDistill.Domain.Entities.DimSource", "Source")
                        .WithMany("FactQuotes")
                        .HasForeignKey("SourceKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Date");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("FinDistill.Domain.Entities.DimAsset", b =>
                {
                    b.Navigation("FactQuotes");
                });

            modelBuilder.Entity("FinDistill.Domain.Entities.DimDate", b =>
                {
                    b.Navigation("FactQuotes");
                });

            modelBuilder.Entity("FinDistill.Domain.Entities.DimSource", b =>
                {
                    b.Navigation("FactQuotes");
                });
#pragma warning restore 612, 618
        }
    }
}
